#treehash

class Tree_Hash
  
  def initialize
    @trees =  {
    :tree1 => {:zip => 10001,
            :species => "Pear Callery",
            :nickname => "Pyrus Calleryana",
            :street => "West 25 Street",
            :diameter => 13},
   :tree2 => {:zip => 10002,
            :species => "",
            :nickname => "",
            :street => "East Houson Street",
            :diameter => 8},
  :tree3 => {:zip => 10003,
            :species => "",
            :nickname => "",
            :street => "4 Avenue",
            :diameter => 13},
  :tree4 => {:zip => 10004,
            :species => "",
            :nickname => "",
            :street => "Washington Street",
            :diameter => 4},
  :tree5 => {:zip => 10005,
            :species => "",
            :nickname => "",
            :street => "Pine Street",
            :diameter => 7},
  :tree6 => {:zip => 10006,
            :species => "",
            :nickname => "",
            :street => "Trinity Place",
            :diameter => 6},
  :tree7 => {:zip => 10007,
            :species => "",
            :nickname => "",
            :street => "West Street",
            :diameter => 4 },
  :tree8 => {:zip => 10009,
            :species => "Sycamore",
            :diameter => 10},
  :tree9 => {:zip => 10010,
            :species => "Sycamore",
            :diameter => 10},
  :tree10 => {:zip => 10011,
            :species => "Sycamore",
            :diameter => 10},
  :tree11 => {:zip => 10012,
            :species => "Sycamore",
            :diameter => 10},
  :tree12 => {:zip => 10013,
            :species => "Sycamore",
            :diameter => 10},
  :tree13 => {:zip => 10014,
            :species => "Sycamore",
            :diameter => 10},
  :tree14 => {:zip => 10016,
    :species => "Sycamore",
            :diameter => 10},
  :tree15 => {:zip => 10017,
            :species => "Sycamore",
            :diameter => 10},
  :tree16 => {:zip => 10018,
            :species => "Sycamore",
            :diameter => 10},
  :tree17 => {:zip => 10019,
            :species => "Sycamore",
            :diameter => 10},
  :tree18 => {:zip => 10020,
            :species => "Sycamore",
            :diameter => 10},
  :tree19 => {:zip => 10021,
            :species => "Sycamore",
            :diameter => 10},
  :tree20 => {:zip => 10022,
            :species => "Sycamore",
            :diameter => 10},
   :tree21 => {:zip => 10023,
            :species => "Sycamore",
            :diameter => 10},
   :tree22 => {:zip => 10024,
            :species => "Sycamore",
            :diameter => 10},
   :tree23 => {:zip => 10025,
            :species => "Sycamore",
            :diameter => 10},
   :tree24 => {:zip => 10026,
            :species => "Sycamore",
            :diameter => 10},
   :tree25 => {:zip => 10027,
            :species => "Sycamore",
            :diameter => 10},
   :tree26 => {:zip => 10028,
            :species => "Sycamore",
            :diameter => 10},
   :tree27 => {:zip => 10029,
            :species => "Sycamore",
            :diameter => 10}
          }
    
  end
  
  attr_accessor :trees
  
  
  
end

 